### PR TITLE
Release 1.0.1

### PR DESCRIPTION
**Pull request by akrherz**

### CODE REVIEW

**Comment by guusdk** [comment]
You're adding a changelog, but that file already exists in the repo. It's under the first directory.

**Comment by akrherz** [comment]
> It's under the first directory.

Oh, they are in the `src` directory.  Is there a reason those files are there and not in the root like the other plugins?

**Comment by guusdk** [comment]
> Oh, they are in the src directory. Is there a reason those files are there and not in the root like the other plugins?

Not really.

**Comment by Fishbowler** [comment]
This got merged, but there hasn't been a release. Is there more work needed?

**Comment by guusdk** [comment]
What went into the tag 1.0.1 turns out to be a non-functional plugin (the code will compile, but Openfire won't load the plugin). I only found out after merging this PR. On master, I've 'corrected' the behavior (by [reverting the first commit](https://github.com/igniterealtime/openfire-threaddump-plugin/commit/91d62f2de300eb1a98bb02b9921c5df29ae9225b) in this PR). As I've added [more functionality in a separate PR](https://github.com/igniterealtime/openfire-threaddump-plugin/pull/7), I figured I wouldn't bother with rewriting history to get the 1.0.1 version out of the door - instead simply focussing on 1.0.2. Not the most elegant of solutions, and I'd not oppose someone doing this in a nicer way.

**Pull request merged**
